# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js

install:
  - ./bin/travis/install.sh

script: |
  [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]] && ./bin/travis/script.sh

before_deploy:
  - ./bin/travis/before_deploy.sh

after_deploy:
  - ./bin/travis/after_deploy.sh

jobs:
  include:
    - stage: test and deploy
      if: branch != master
      script: ./bin/travis/script.sh
    - # stage name not required, will continue to use `test and deploy`
      deploy:
        skip_cleanup: true
        provider: script
        script: ./bin/travis/deploy.sh
        on:
          all_branches: true
    - stage: deploy
      if: branch = master
      deploy:
        skip_cleanup: true
        provider: script
        script: ./bin/travis/deploy.sh
        on:
          all_branches: true
